# Welcome to Jekyll!
#

# Site settings
title: Dear to the Heart
description: Making AAC as free as possible through social awareness, global supports, and open standards
owner: Dear to the Heart # or company name
first_published: 2026 # if migrating another site, the year of your first publish
email: dear@openaac.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.deartotheheart.org" # the base hostname & protocol for your site
social:
  instagram: https://www.instagram.com/dear.to.the.heart
  facebook: https://www.facebook.com/profile.php?id=61585111330491

# Build settings
markdown: kramdown
#sass:
#  style: compressed
